version: '2.3'

services:
    llvm-9:
        image: llvm:9
        build:
            context: .
            dockerfile: llvm-9.Dockerfile
        volumes:
            - ..:/mnt
        working_dir: /mnt
