name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DOCKER_RUN : "RETURN_CODE=$?; chown -R $(stat -c '%u:%g' /mnt) /mnt; exit ${RETURN_CODE}"
        steps:
            - uses: actions/checkout@master
            - name: Assignment 0 Introduction to Docker
              run: docker-compose build cscd70-dev
            - name: Assignment 1 Introduction to LLVM
              run: |
                   docker-compose run --rm \
                       -w /mnt/Assignment1-Introduction_to_LLVM/FunctionInfo \
                       cscd70-dev bash -ce \
                      "mkdir build && cd build; cmake .. && make && ctest"
                   docker-compose run --rm \
                       -w /mnt/Assignment1-Introduction_to_LLVM/LocalOpts \
                       cscd70-dev bash -ce \
                      "mkdir build && cd build; cmake .. && make && ctest"
            - name: Tutorial 1 Introduction to LLVM
              run: |
                   docker-compose run --rm \
                       -w /mnt/Tutorial1-Introduction_to_LLVM/Example1-Cpp_PReview \
                       cscd70-dev bash -ce \
                      "make && ./VarReference && ./PublicInheritance && ./STL"
