name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: LLVM Docker
              working-directory: 0-LLVM_Docker
              run: docker-compose up llvm-6_0
            - name: Assignment1
              working-directory: 0-LLVM_Docker
              run: docker-compose run --rm -w /mnt/Assignment1-Introduction_to_LLVM/FunctionInfo llvm-6_0 make
            - name: Tutorial1
              working-directory: 0-LLVM_Docker
              run: docker-compose run --rm -w /mnt/Tutorial01-Introduction_to_LLVM/Example1-Cpp_Fundamentals llvm-6_0 make
            - name: Tutorial2
              working-directory: 0-LLVM_Docker
              run: |
                   docker-compose run --rm -w /mnt/Tutorial02-Introduction_to_LLVM_ii/Example1-Transform llvm-6_0 make
                   docker-compose run --rm -w /mnt/Tutorial02-Introduction_to_LLVM_ii/Example2-Pass_Manager llvm-6_0 make
            - name: (Experimental) LLVM 9
              working-directory: experimental/llvm-9
              run: |
                   docker-compose up llvm-9
                   docker-compose run --rm llvm-9 bash -ce "mkdir -p build; cd build; cmake ..; make; make test"
