name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Assignment 0 Introduction to Docker
              run: docker-compose build cscd70-dev
            - name: Assignment 1 Introduction to LLVM
              run: |
                   docker-compose run --rm \
                       -w /mnt/Assignment1-Introduction_to_LLVM/FunctionInfo \
                       cscd70-dev bash -ce \
                      "mkdir build && cd build; cmake .. && make && ctest"
                   docker-compose run --rm \
                       -w /mnt/Assignment1-Introduction_to_LLVM/LocalOpts \
                       cscd70-dev bash -ce \
                      "mkdir build && cd build; cmake .. && make && ctest"
            - name: Tutorial 1 Introduction to LLVM
              run: |
                   docker-compose run --rm \
                       -w /mnt/Tutorial1-Introduction_to_LLVM/Example1-Cpp_PReview \
                       cscd70-dev bash -ce \
                      "make && ./VarReference && ./PublicInheritance && ./STL"
            - name: Tutorial 2 Introduction to LLVM ii
              run: |
                   docker-compose run --rm \
                       -w /mnt/Tutorial2-Introduction_to_LLVM_ii/Example1-Transform_Pass_Sample \
                       cscd70-dev bash -ce \
                      "mkdir build && cd build; cmake .. && make && ctest"
                   docker-compose run --rm \
                       -w /mnt/Tutorial2-Introduction_to_LLVM_ii/Example2-Pass_Manager \
                       cscd70-dev bash -ce \
                      "mkdir build && cd build; cmake .. && make && ctest"
            - name: C to LLVM IR
              run: docker-compose run --rm -w /mnt/Tools/C_to_LLVM_IR cscd70-dev make
