name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: LLVM Docker
              run: docker-compose build llvm-6_0
            - name: Assignment1
              run: docker-compose run --rm -w /mnt/Assignment1-Introduction_to_LLVM/FunctionInfo llvm-6_0 make
            - name: Assignment2
              run: docker-compose run --rm -w /mnt/Assignment2-Dataflow_Analysis llvm-6_0 make
            - name: Tutorial1
              run: docker-compose run --rm -w /mnt/Tutorial01-Introduction_to_LLVM/Example1-Cpp_Fundamentals llvm-6_0 make
            - name: Tutorial2
              run: |
                   docker-compose run --rm -w /mnt/Tutorial02-Introduction_to_LLVM_ii/Example1-Transform    llvm-6_0 make
                   docker-compose run --rm -w /mnt/Tutorial02-Introduction_to_LLVM_ii/Example2-Pass_Manager llvm-6_0 make
            - name: Tutorial4
              run: docker-compose run --rm -w /mnt/Tutorial04-Static_Single_Assignment/Example1-SSA llvm-6_0 make
