name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: CSCD70 Docker
              run: docker-compose build cscd70-dev
            - name: Assignment1
              run: docker-compose run --rm -w /mnt/Assignment1-Introduction_to_LLVM/FunctionInfo cscd70-dev make
            - name: Assignment2
              run: docker-compose run --rm -w /mnt/Assignment2-Dataflow_Analysis cscd70-dev make
            - name: Tutorial1
              run: docker-compose run --rm -w /mnt/Tutorial01-Introduction_to_LLVM/Example1-Cpp_Fundamentals cscd70-dev make
            - name: Tutorial2
              run: |
                   docker-compose run --rm -w /mnt/Tutorial02-Introduction_to_LLVM_ii/Example1-Transform    cscd70-dev make
                   docker-compose run --rm -w /mnt/Tutorial02-Introduction_to_LLVM_ii/Example2-Pass_Manager cscd70-dev make
            - name: Tutorial4
              run: docker-compose run --rm -w /mnt/Tutorial04-Static_Single_Assignment/Example1-SSA cscd70-dev make
