name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                persist-credentials: false
            - name: Sphinx
              run: pip3 install sphinx
            - name: Build
              run: cd Website && make html
            - name: Publish
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: Website/build
